# Generated by Django 4.1.2 on 2022-10-30 16:57
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                default="", max_length=10, verbose_name="Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=32, verbose_name="Password"),
        ),
    ]
