# Generated by Django 4.1.2 on 2022-10-30 16:58
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_user", "0002_user_phone_number_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                default="",
                max_length=10,
                unique=True,
                verbose_name="Phone Number",
            ),
        ),
    ]
